apiVersion: v1
kind: Pod
metadata:
  name: geoflow-uploader
spec:
  restartPolicy: Never
  containers:
    - name: uploader
      image: alpine@sha256:d9e853e87e55526f6b2917df91a2115c36dd7c696a35be12163d44e6e2a4b6bc
      imagePullPolicy: IfNotPresent
      command:
        - sh
        - -c
        - sleep 604800
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: workspace
          mountPath: /workspace
  volumes:
    - name: workspace
      persistentVolumeClaim:
        claimName: geoflow-pvc
